# Generated by Django 4.2.4 on 2023-09-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tercera_entrega', '0002_metaahorro_itemgasto_fecha_delete_gastomensual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
