# Generated by Django 4.2.5 on 2023-09-13 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tercera_entrega', '0003_contactos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contactos',
        ),
    ]
