# Generated by Django 4.2.5 on 2023-10-02 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tercera_entrega', '0008_alter_categoriagasto_usuario_alter_itemgasto_usuario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetaAhorro',
        ),
    ]
